modify

diff --git a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
--- a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
+++ b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
@@ -2,8 +2,15 @@ steps:
 - script: |
     set -x
 
-    DIFF_FOLDERS=$(git diff HEAD^ HEAD --name-only | xargs -n1 dirname | sort -u | tr '\n' ' ') || ""
-    echo -n "##vso[task.setvariable variable=DIFF_FOLDERS]$DIFF_FOLDERS"
+    DIFF_FOLDERS=$(git diff HEAD^ HEAD --name-only | xargs -n1 dirname | sort -u | tr '\n' ' ')
+
+    if [[ -z "$DIFF_FOLDERS" ]]; then
+      echo "##vso[task.complete result=Failed;]Get diff folders fail."
+      exit 1
+    else
+      echo -n "##vso[task.setvariable variable=DIFF_FOLDERS]$DIFF_FOLDERS"
+    fi
+  continueOnError: false
   displayName: "Get diff folders"
 
 - script: |
@@ -50,14 +57,15 @@ steps:
     done
 
     if [[ -z "$FINAL_FEATURES" ]]; then
-      TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/get_test_scripts.py --features "" --location tests)
+      TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/get_test_scripts.py --features "" --location tests) || ""
     else
-      TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/get_test_scripts.py --features ${FINAL_FEATURES} --location tests)
+      TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/get_test_scripts.py --features ${FINAL_FEATURES} --location tests) || ""
     fi
 
-    PR_CHECKERS=$(echo "${TEST_SCRIPTS}" | jq -c 'keys')
+    PR_CHECKERS=$(echo "${TEST_SCRIPTS}" | jq -c 'keys') || ""
 
     echo "##vso[task.setvariable variable=PR_CHECKERS;isOutput=true]$PR_CHECKERS"
     echo "##vso[task.setvariable variable=TEST_SCRIPTS;isOutput=true]$TEST_SCRIPTS"
   name: SetVariableTask
+  continueOnError: false
   displayName: "Get impacted area"
